name: Build DirtyJTAG

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:   # Add this line for manual trigger

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: alpine:3.14

    steps:
    - name: Install dependencies
      run: |
        apk add --no-cache python2 make gcc-arm-none-eabi newlib-arm-none-eabi

    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up DirtyJTAG
      run: |
        cd dirtyjtag
        git submodule init
        git submodule update

    - name: Build for BluePill
      run: |
        cd dirtyjtag
        make PLATFORM=bluepill

    - name: Build for STLinkV2
      run: |
        cd dirtyjtag
        make PLATFORM=stlinkv2

    - name: Build for STLinkV2 DFU
      run: |
        cd dirtyjtag
        make PLATFORM=stlinkv2dfu

    - name: Build for Baite
      run: |
        cd dirtyjtag
        make PLATFORM=baite

    - name: Build for Olimex STM32H103
      run: |
        cd dirtyjtag
        make PLATFORM=olimexstm32h103

    - name: Build for STLinkV2 White
      run: |
        cd dirtyjtag
        make PLATFORM=stlinkv2white

    - name: Upload BluePill artifact
      uses: actions/upload-artifact@v3
      with:
        name: bluepill
        path: dirtyjtag/build/bluepill

    - name: Upload STLinkV2 artifact
      uses: actions/upload-artifact@v3
      with:
        name: stlinkv2
        path: dirtyjtag/build/stlinkv2

    - name: Upload STLinkV2 DFU artifact
      uses: actions/upload-artifact@v3
      with:
        name: stlinkv2dfu
        path: dirtyjtag/build/stlinkv2dfu

    - name: Upload Baite artifact
      uses: actions/upload-artifact@v3
      with:
        name: baite
        path: dirtyjtag/build/baite

    - name: Upload Olimex STM32H103 artifact
      uses: actions/upload-artifact@v3
      with:
        name: olimexstm32h103
        path: dirtyjtag/build/olimexstm32h103

    - name: Upload STLinkV2 White artifact
      uses: actions/upload-artifact@v3
      with:
        name: stlinkv2white
        path: dirtyjtag/build/stlinkv2white
