name: Build DirtyJTAG

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y git build-essential gcc-arm-none-eabi libnewlib-arm-none-eabi openocd

    - name: Clone submodules
      run: git submodule update --init --recursive

    - name: Compile DirtyJTAG
      run: |
        cd software
        make

    - name: Archive build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: dirtyjtag-bin
        path: |
          software/build/*
